### PR TITLE
Add metadata generation hooks and metadata registration

### PR DESCRIPTION
**Pull request by nitinja**
## Description
Adds hook to generate and verify metadata from app.config.yaml. Adds the generated metadata to extension registration.

## Related Issue
https://jira.corp.adobe.com/browse/SITES-17283

## Motivation and Context

We would like to generate metadata file from yaml configuration.
This will enable us to convey extension-related config to host, in cases where info from registry not available or feasible.
Generated metadata will be sent to host.

## How Has This Been Tested?
Tested manually by generating extension and local testing using ext param, the main use case.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by fe-lix- — COMMENTED** [review]
LGTM.

**Comment by fe-lix-** [comment]
Whatch out @nitinja you are using the internal repository in the `yarn.lock` which results in build job issues.

**Review by fe-lix- — CHANGES_REQUESTED** [review]
LGTM but the build is failing due to this being change to an internal corp repository which is not available for public packages.

**Comment by nitinja** [comment]
OKey, I am looking into it, removing any internal references. Will merge only if build succeeds.

**Pull request merged**
